[32m2023-10-29 17:43:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99f500c0-279b-4437-9b1a-28adea253859 - 19209 - LOGS_CAPTURED - Started capturing logs in process (pid: 19209).
[32m2023-10-29 17:43:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 99f500c0-279b-4437-9b1a-28adea253859 - 19209 - storm_data_large - STEP_START - Started execution of step "storm_data_large".
[32m2023-10-29 17:43:34 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 99f500c0-279b-4437-9b1a-28adea253859 - 19209 - storm_data_large - STEP_FAILURE - Execution of step "storm_data_large" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "storm_data_large"::

pyarrow.lib.ArrowTypeError: object of type <class 'str'> cannot be converted to int

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 461, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/workspaces/DSP/src/dsp-dagster/dsp_dagster/assets/fire_department_data.py", line 24, in storm_data_large
    df = pl.from_pandas(df)
  File "/usr/local/lib/python3.10/site-packages/polars/convert.py", line 714, in from_pandas
    return pl.DataFrame._from_pandas(
  File "/usr/local/lib/python3.10/site-packages/polars/dataframe/frame.py", line 644, in _from_pandas
    pandas_to_pydf(
  File "/usr/local/lib/python3.10/site-packages/polars/utils/_construction.py", line 1701, in pandas_to_pydf
    arrow_dict[str(col)] = _pandas_series_to_arrow(
  File "/usr/local/lib/python3.10/site-packages/polars/utils/_construction.py", line 607, in _pandas_series_to_arrow
    return pa.array(values, from_pandas=nan_to_null)
  File "pyarrow/array.pxi", line 323, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
[0m
